version: "3.9"

services:
  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
    environment:
      N8N_HOST: automation.sterveshop.cloud
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://automation.sterveshop.cloud/
      NODE_ENV: production
      TZ: Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`automation.sterveshop.cloud`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
    networks:
      - traefik
    volumes:
      - ./n8n_data:/home/node/.n8n

networks:
  traefik:
    external: true
