services:
  frontend:
    build: ./frontend
    container_name: site-vitrine-frontend
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"

      # HTTP
      - "traefik.http.routers.site-vitrine.rule=Host(`vitrine.sterveshop.cloud`)"
      - "traefik.http.routers.site-vitrine.entrypoints=web"

      # HTTPS
      - "traefik.http.routers.site-vitrine-secure.rule=Host(`vitrine.sterveshop.cloud`)"
      - "traefik.http.routers.site-vitrine-secure.entrypoints=websecure"
      - "traefik.http.routers.site-vitrine-secure.tls=true"
      - "traefik.http.routers.site-vitrine-secure.tls.certresolver=letsencrypt"

      # Service
      - "traefik.http.services.site-vitrine.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true
