version: "3.8"

services:
  lab:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    container_name: lab
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./lab_data:/data
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.lab.rule=Host(`lab.sterveshop.cloud`)
      - traefik.http.routers.lab.entrypoints=websecure
      - traefik.http.routers.lab.tls.certresolver=le
      - traefik.http.services.lab.loadbalancer.server.port=80

networks:
  web:
    external: true
