http:
  routers:
    n8n:
      rule: Host(`n8n.srv1191236.hstgr.cloud`)
      entryPoints:
        - websecure
      service: n8n
      tls:
        certResolver: mytlschallenge

  services:
    n8n:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"
