version: "3.9"

services:
  builder:
    build: .
    container_name: builder-site
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.builder.rule=Host(`builder.sterveshop.cloud`)"
      - "traefik.http.routers.builder.entrypoints=websecure"
      - "traefik.http.routers.builder.tls=true"
      - "traefik.http.routers.builder.tls.certresolver=letsencrypt"
      - "traefik.http.services.builder.loadbalancer.server.port=80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
